JIRA-Software:
  hostname: JIRA
  image: jeroenskie/jira:7.2.6
  volumes:
  - /data/jira/home:/var/atlassian/jira
  - /data/jira/log:/opt/atlassian/jira/logs
  environment:
    JAVA_OPTS: -Djava.awt.headless=true -Xms1024m -Xmx2048m
  ports:
  - "8080:8080"
