version: '2'
networks:
   lb_web:
   external: true
  back:
    driver: bridge
services:
  db:
    image: mysql
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - back
  app:
    image: piwik
    links:
      - db
    volumes:
      - /data/piwik/config:/var/www/html/config
    networks:
      - back
  web:
    image: nginx
    volumes:
      - /data/piwik/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
    ports:
      - "8080:80"
      - "8443:443"
  cron:
    image: piwik
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
      - back