.catalog:
  name: Piwik Open Analytics Platform
  version: 3.2.1
  description: Open-Source analytics platform https://piwik.org
  uuid: piwik-software-3-2-1

services:    
  web:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 81
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
      
    