.catalog:
  name: Piwik Open Analytics Platform
  version: 3.2.1
  description: Open-Source analytics platform https://piwik.org
  uuid: piwik-software-3-2-1

JIRA-Software:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    response_timeout: 2000
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
   
